# Generated by Django 3.1 on 2020-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=40)),
                ('cedula', models.IntegerField()),
                ('telefono', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('ip', models.CharField(max_length=30)),
            ],
        ),
    ]
