# Generated by Django 3.1 on 2020-08-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_auto_20200819_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='City',
        ),
    ]
